const prompt = require("prompt-sync")();
console.clear()
// let num1 = +prompt('digite o primeiro numero ')
// let num2 = +prompt('Digite o segundo numero ')


// console.log(num1 + num2)
// console.log(num1 - num2)
// console.log(num1 * num2)
// console.log(num1 / num2)


// console.log();

let tempo = prompt('Como está o tempo?')

if (tempo=="sol"){
    console.log('vai sair');
} else if(tempo ==="nublado"){
    console.log('Vai jogar na rua')
} 


else{
console.log('vai jogar video game')
}


console.log();
