// console.clear()



// console.log('Olá, mundo!');
// let nome = 'Petterson b';
// let idade = '39';       
// console.log(nome);

// console.log()

// const Prompt = require('prompt-sync')();
// console.clear()

// //  nome = prompt("Digite seu nome: ");

// console.log("Digite seu nome: ")
// console.log("bem vindo", nome) 

const prompt = require("prompt-sync")();

let num1 = +prompt('digite o primeiro numero ')
let num2 = +prompt('Digite o segundo numero ')


console.log(num1 + num2)
console.log(num1 - num2)
console.log(num1 * num2)
console.log(num1 / num2)


console.log();